import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//     // By default, Docusaurus generates a sidebar from the docs folder structure
//     tutorialSidebar: [{
//         type: 'autogenerated', dirName: '.'
//     }],

//     // But you can create a sidebar manually
//     /*
//     tutorialSidebar: [
//       'intro',
//       'hello',
//       {
//         type: 'category',
//         label: 'Tutorial',
//         items: ['tutorial-basics/create-a-document'],
//       },
//     ],
//      */
// };

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        'introduction',
        'quick_start',
        {
            type: 'category',
            label: 'Hardware',
            link: {
                type: 'generated-index'
            },
            collapsed: true,
            items: [
                'hardware/hardware_overview',
                'hardware/hardware_assembly',
            ]
        },
        {
            type: 'catergory',
            label: 'Software',
            link: {
                type: 'generated-index'
            },
            collapsed: true,
            items: [
                'software/arduino_setup',
                'software/arduino_example',
            ]
        },
        'resources',
        {
            type: 'category',
            label: 'Support',
            link: {
                type: 'generated-index'
            },
            collapsed: true,
            items: [
                'support/troubleshooting',
                'support/file_issue',
                'support/contribute'
            ]
        }
    ]
};

export default sidebars;
